[profile.default]
src = 'src'
out = 'foundry-out'
libs = ["lib"]
solc_version = '0.8.26'
optimizer_runs = 999999
via_ir = true
ffi = true
gas_limit = "3000000000"
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./foundry-out" },
    { access = "read", path = "./script/config" },
    { access = "read", path = "./test/pool-cl/dynamic-fee/test" },
]
evm_version = 'cancun'

[fuzz]
runs = 1000 # change this for higher number of fuzz/invariant locally